---
title: "Tyre wear emission model based on friction"
author: "J.T.K. Quik and J. Meesters"
date: "`r Sys.Date()`"
output: md_document
---

# Tyre wear emission model based on friction

This repository contains the model code and model analyses conducted on the newly developed Tyre Wear emission model (Meesters and Quik, 2023).

This work was done as part of the LEON-T project and has reseived funding from the European Union's Horizon 2020 research and innovation programme under grant agreement 955397.

-   Meesters, J. and Quik, J.T.K., 2023, Updated emission model for local and EU scale, Deliverable 3.4 for the LEON-T project.

## Installation

Create a new version based project in Rstudio using this repository.

## Usage

Go through this vignette: [Estimating the abrasion coefficient](vignettes/Estimating_abr_coef_SIML.Rmd "getting started").

## Contributing

Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

## License

[EUPL](https://choosealicense.com/licenses/eupl-1.2/#)
